### ISSUE TITLE
Firewall: 'iptables' finished with error: <nil>

### ISSUE THREAD

**Issue by suurltd** [nccgroup/singularity#11]
The framework works great while using the rebinding strategy "First than second". 
But if i try out the  "Multiple answers" strategy there occus an error the following error  'iptables' finished with error:  nil 
As a result, no firewall rule is created and the requests are not blocked.
Can you give me a hint about what goes wrong?

**Comment by gdncc** [comment]
This log message is misleading and in this case probably means no error ('nil') happened server side.

I assume you run Singularity on Linux with iptables server-side.

Did you set the interval to "1" second? This technique was successfully tested with this interval only.

Are you targeting your host or another host on the network? This technique was successfully tested against 'localhost' type of target specification only.

If targeting 'localhost', ensure that you set the target IP address to '127.0.0.1' on Windows and to '0.0.0.0' on Linux/macos.
