### ISSUE TITLE
{"ServerInformation":[{"Port":"80"}],"AllowDynamicHTTPServers":false}

### ISSUE THREAD

**Issue by BelpheGor13** [nccgroup/singularity#20]
i have problem ...and i added the dot but its not secces..
and thats hpend when local target or public >>im the local aand public ...
root@kali:~/singularity# ./singularity-server --HTTPServerPort 80 --ResponseIPAddr 192.168.1.5 --ResponseReboundIPAddr 192.168.1.6
Temporary secret: d4c7b6ea906748c73d054dab7de931b304250dda
2020/01/05 23:50:12 Main: Starting DNS Server at 53
2020/01/05 23:50:12 HTTP: starting HTTP Server on :80
2020/01/05 23:50:12 HTTP: starting HTTP Websockets/Proxy Server on :3129
2020/01/05 23:50:39 HTTP: GET / from [::1]:52888
2020/01/05 23:50:41 HTTP: GET /manager.html from [::1]:52890
2020/01/05 23:50:41 HTTP: GET /manager.js from [::1]:52892
2020/01/05 23:50:41 HTTP: GET /servers from [::1]:52894
{"ServerInformation":[{"Port":"80"}],"AllowDynamicHTTPServers":false}
2020/01/05 23:50:41 HTTP: GET /manager-config.json from [::1]:52896

**Comment by sanktjodel** [comment]
Can you please provide some more information:

- What are you trying to achieve and what exactly fails?
- Do you get an error message?
- Can you reach the manager web interface?
- What browser did you use?
- What target and payload type did you use?
- What is your local DNS configuration?

**Comment by BelpheGor13** [comment]
> Can you please provide some more information:
> 
>     * What are you trying to achieve and what exactly fails?
> 
>     * Do you get an error message?
> 
>     * Can you reach the manager web interface?
> 
>     * What browser did you use?
> 
>     * What target and payload type did you use?
> 
>     * What is your local DNS configuration?

I am trying to transfer requests from another router or an external target (me too) and used the simple code .. and the browser Firefox and Chrome .. and the DNS No IP .. Also I think that the tool needs to explain the budgets in more detail

**Comment by sanktjodel** [comment]
I don't understand what exactly fails. Please try to explain what you are trying to achieve and how it fails and provide as much information as possible so that we can help.

There is also some documentation on the wiki: https://github.com/nccgroup/singularity/wiki

**Comment by BelpheGor13** [comment]
> I don't understand what exactly fails. Please try to explain what you are trying to achieve and how it fails and provide as much information as possible so that we can help.
> 
> There is also some documentation on the wiki: https://github.com/nccgroup/singularity/wiki
Thanks for your reply ..
I am trying to change the DNS requests .. on another router .. by adding a NOIP to the other router .. then I put the public IP in the tool .. then it shows me the error that I showed earlier

**Comment by gdncc** [comment]
There is no error in the log above. The log entry `{"ServerInformation":[{"Port":"80"}],"AllowDynamicHTTPServers":false}` is just information sent from the Singularity server about its configuration to the Singularity JavaScript code running in the browser.

**Comment by BelpheGor13** [comment]
> There is no error in the log above. The log entry `{"ServerInformation":[{"Port":"80"}],"AllowDynamicHTTPServers":false}` is just information sent from the Singularity server about its configuration to the Singularity JavaScript code running in the browser.

But it does not provide me with the results of the requests sent from the target ..

**Comment by gdncc** [comment]
Not enough information provided.
