### ISSUE TITLE
Option to support all ports via tproxy

### ISSUE THREAD

**Issue by ilsken** [nccgroup/singularity#22]
Currently, singularity has to be configured with ports at startup or be configured to dynamically bind to ports with the "dangerously allow request ports" option.

If you have a dedicated IP address for singularity on the machine, it may be possible to use the tproxy module in linux along with SO_TRANSPARENT socket option to redirect incoming connections on all ports for that IP to singularity.

Cloudflare has a [great blog post](https://blog.cloudflare.com/how-we-built-spectrum/) on how to accomplish this.

Alternatively, if Singularity supported the `PROXY` protocol, users could set up this trick and forward traffic to Singularity with the original/port available in headers sent to the application

**Comment by gdncc** [comment]
Thank you. tproxy support is an interesting idea and we will look into it.

**Comment by gdncc** [comment]
Branch https://github.com/nccgroup/singularity/tree/feature/tproxy includes experimental support for tproxy. I've performed a quick test from 80 -> 8080 with the multiple answers rebinding strategy and it seems to work well. Further testing is required for all strategies and features such as hook and control/scanning etc.

**Comment by ilsken** [comment]
Wow that was quick! I'm glad to hear the test went well, I will give it a try after work. Thank you for taking the time to look at this. Your work/research is very much appreciated

**Comment by gdncc** [comment]
Merged to main branch.
