### ISSUE TITLE
what about adding a tunneling feature for more control and monitoring if everything is going as it should ?

### ISSUE THREAD

**Issue by minanagehsalalma** [nccgroup/singularity#25]

**Comment by minanagehsalalma** [comment]
@ChaosData just like this 

https://portswigger.net/daily-swig/new-tool-enables-dns-rebinding-tunnel-attacks-without-reconnaissance

https://youtu.be/sqUxeiqq0xE

**Comment by gdncc** [comment]
Tunneling is implemented in Singularity. Check https://youtu.be/y9-0lICNjOQ?t=1326

**Comment by minanagehsalalma** [comment]
> Tunneling is implemented in Singularity. Check https://youtu.be/y9-0lICNjOQ?t=1326

That's real great  you should add it to the readme.
