### ISSUE TITLE
Configuration (Google cloud + gandi)

### ISSUE THREAD

**Issue by blogNetting** [nccgroup/singularity#28]
Hello:

In this link: https://github.com/nccgroup/singularity/wiki/Setup-and-Installation. You indicate that gandi or namecheap is used. And a Linux instance of some of these: Linode, Amazon AWS, Google Cloud, Microsoft Azure etc.

I understand that you have tried any of these combinations.

In my case I have tried with gandi and with Google Cloud and Azure. But I cannot connect an external machine with the instance through the DNS protocol (53).

I have an Ubuntu 18 installed on the MV. And I have disabled the systemd-resolved service as indicated in the documentation.
![image](https://user-images.githubusercontent.com/30011648/80249986-277bb080-8673-11ea-8e9c-84ff29396ddf.png)

He permitido la entrada de todos los protocolos. Pero no puedo conectarme a través del puerto 53 UDP. 

![image](https://user-images.githubusercontent.com/30011648/80250472-3c0c7880-8674-11ea-885c-f824f0ecbe34.png)

The connection is established through: nc local_ip 53 -u. It is as if the Azure / google Cloud firewall filters or uses port 53.

**Any idea how to fix this? You've done it?**

My /etc/resolv.conf file:

_nameserver 8.8.8.8
options edns0
search europe-west4-b.c.handy-zephyr-275214.internal c.handy-zephyr-275214.internal google.internal_

I understand that the domain server can only communicate with the instance through port 53, which I cannot change. Do NAT type 5353 -> 53

Regarding the domain configuration, you would only have to modify this, is that so?

![image](https://user-images.githubusercontent.com/30011648/80251124-61e64d00-8675-11ea-9d6f-b866848e2ab9.png)

For this:

@ 10800 IN SOA ns1.gandi.net. hostmaster.gandi.net. 1554761168 10800 3600 604800 10800
@ 3600 IN A VM_IP
d 1800 IN NS nettinghack.site.
\* 1800 IN A VM_IP

Thanks a lot!

**Comment by sanktjodel** [comment]
We have successfully deployed Singularity on GCP. Please check the following:

1. There might be a local firewall (e.g. iptables) on your Ubuntu system preventing access to DNS. Check if the firewall is enabled (e.g. sudo ufw status or sudo iptables -L -n)
2. Try to run netstat with the -l parameter to show listening sockets (e.g. sudo netstat -lnp)
3. Do you get any error when running Singularity?

**Comment by blogNetting** [comment]
Hi:

![image](https://user-images.githubusercontent.com/30011648/80266209-09c24180-869b-11ea-942f-f808caeb2170.png)

**Comment by blogNetting** [comment]
> Do you get any error when running Singularity?

No. No. I have not installed yet. First I wanted to check that there was connectivity between the domain and the GCP instance by DNS (53). Otherwise, I know it won't work.

Anyway. Would the gandi configuration be this?

@ 10800 IN SOA ns1.gandi.net. hostmaster.gandi.net. 1554761168 10800 3600 604800 10800
@ 3600 IN A VM_IP
d 1800 IN NS nettinghack.site.
\* 1800 IN TO VM_IP

![image](https://user-images.githubusercontent.com/30011648/80266442-2f037f80-869c-11ea-8ec0-f7251bbffb21.png)

As you can see your.
There is connectivity at the local network level. I use the machine's private IP address to connect. Even using the private IP address. Something that shouldn't work ...

If I try to connect from the outside, simulating, for example, being the domain, I would not have connectivity.

Everything seems to indicate that the GCP firewall is filtering the port or using it. The same thing happens to me with the home router and with an Azure instance.

Thanks for the reply.

**Comment by sanktjodel** [comment]
Sounds like you have a networking issue and not an issue with Singularity.

Maybe your ISP is blocking egress DNS. You can try if your DNS connection works from an Azure instance to your GCP instance.

**Comment by blogNetting** [comment]
Hi:

Effectively. It was my ISP, it was filtered of dns. Between the MVs if there was connectivity.

Could you confirm that this is the configuration for the DNS domain?

@ 10800 IN SOA ns1.gandi.net. hostmaster.gandi.net. 1554761168 10800 3600 604800 10800
@ 3600 IN A VM_IP
d 1800 IN NS nettinghack.site.
\* 1800 IN TO VM_IP

Thanks!

**Comment by sanktjodel** [comment]
The DNS configuration looks correct.
