### ISSUE TITLE
Hook And Control DNS record broke the script on some providers.

### ISSUE THREAD

**Issue by edduu** [nccgroup/singularity#29]
There is an issue with some DNS providers for example Cloudflare.

Hook and Control requires add a wildcard (*) A record to yourdomain.com

so ANY.yourdomain.com will resolve to lets suppose 163.172.XX.XX
but *.dynamic.yourdomain.com will use the DNS server on 163.172.XX.XX and will switch between that IP and victim.

Here comes the conflict, when I add wildcard to cloudflare, and I do NSLOOKUP

Requests will return on duplicate with those rules.

The first request will return 

```
C:\Users\Win>nslookup s-163.172.XX.XX-127.0.0.1-33782548737-ma-e.dynamic.yourdomain.com
Server:  dns.google
Address:  8.8.8.8

Non-authoritative answer:
Name:    s-163.172.XX.XX-127.0.0.1-33782548737-ma-e.dynamic.yourdomain.com
Addresses:  163.172.XX.XX
          163.172.XX.XX

```
The second 
```
C:\Users\Win>nslookup s-163.172.XX.XX-127.0.0.1-33782548737-ma-e.dynamic.yourdomain.com
Server:  dns.google
Address:  8.8.8.8

Non-authoritative answer:
Name:    s-163.172.XX.XX-127.0.0.1-33782548737-ma-e.dynamic.yourdomain.com
Addresses:  163.172.XX.XX
          127.0.0.1

```

It follow both rules, the wildcard one, that resolves to 163.172.X and on the second request 10 seconds later to 127.0.0.1

on windows, it makes resolves always to 163.172.X.X

on linux, it doesn't resolves at all.

The possible solution:

Modify 1 or 2 lines in the source to route the sessionid to other subdomain

for example *.dynamic.yourdomain.com for rebinding

and *.tunnel.yourdomain.com

and we add a *.tunnel rule to forward the hostnames to the WS app.

Sadly I am not very familiar with this source and pretty new at golang

The partial solution that I made is remove that *, manually add soohocked A record, and when I want to tunnel to some session I manually add the record to /etc/hosts file.

I am pretty sure much of us uses cloudflare dns, standard domain provider DNS are not that flexible don't give free SSL certs and proxies etc.

Thanks for reading and hope it fixed on a further release.

**Comment by gdncc** [comment]
Hi, I've got Hook and Control working with Cloudflare's  managed DNS service with the following configuration in the “DNS management for attacker.com” screen of the CloudFlare dashboard:

Type, Name, Content, TTL, Proxy status

A, *, xxx.xxx.xxx.xxx, 2 min, DNS only
A, attacker.com, xxx.xxx.xxx.xxx, 2min, DNS only
NS, d, attacker.com, 2min, DNS only

I was able to connect to http://soohooked.attacker.com:3129/ and browse the victim service on localhost using the "Multiple Answers" DNS rebinding strategy

I see you used the “Multiple Answers” (ma) DNS rebinding strategy. Note that you must have the right operating conditions for this to work. For instance, you must set the victim IP address to “0.0.0.0” for the attack to work on Linux. I strongly suggest you try to get this working with the “First Then Second” DNS rebinding strategy first. Then, you can experiment with more advanced techniques.
