### ISSUE TITLE
SOP, Blocked requests

### ISSUE THREAD

**Issue by blogNetting** [nccgroup/singularity#30]
Hi.

Files:

![imagen](https://user-images.githubusercontent.com/30011648/81505253-3064b700-92ee-11ea-80bc-9021b123c151.png)

![imagen](https://user-images.githubusercontent.com/30011648/81505239-1c20ba00-92ee-11ea-8e90-eec4c7e74543.png)

![imagen](https://user-images.githubusercontent.com/30011648/81505277-568a5700-92ee-11ea-9072-ebaa92cef7da.png)

![imagen](https://user-images.githubusercontent.com/30011648/81505317-90f3f400-92ee-11ea-8211-0f921f7d62e3.png)

It's okay. The router / gateway HTTP server has iframes protection enabled.

But why can't I connect via AJAX connection?

I have inserted in the code of the file manager.html jQuery and the function get()

![imagen](https://user-images.githubusercontent.com/30011648/81505358-ea5c2300-92ee-11ea-932c-537295b6ad6c.png)

However:

![imagen](https://user-images.githubusercontent.com/30011648/81505384-19729480-92ef-11ea-8644-5a62f4028441.png)

![imagen](https://user-images.githubusercontent.com/30011648/81505409-33ac7280-92ef-11ea-930e-b4927246c5e6.png)

What is the problem?

Thank you!

**Comment by gdncc** [comment]
The "Attack Host" form field and `attackHostIPAddress` variable should be set to the IP address of the Singularity server, not of the victim's IP address. If you see errors due to the `X-FRAME-OPTIONS` header, then DNS rebinding has not happened.

**Comment by blogNetting** [comment]
Sorry, I didn't understand what you mean.

Could it be more descriptive?

What IP address should I use? The public of singularity?

**Comment by gdncc** [comment]
> The public of singularity?

Yep.
