### ISSUE TITLE
Parsed query error: <nil>

### ISSUE THREAD

**Issue by grenej** [nccgroup/singularity#31]
Hello,

I have setup DNS domain (called MYDOMAIN.COM) on Gandi.net and Singularity server in Azure (Redhat 8.1)  called SINGULATITY_SERVER_IP.
I have added required entries to Gandi.net DNS and opened UDP 53 and TCP 80 port on Singulatiry serwer.
In my local network, I have printer which provides Web page for management available in my local network under IP address 192.168.1.48.
I am able to access printer web page without authentication from my laptop (in the same local network). Curl command also gets the results when I query printer web page from laptop.
I have made tests with connection to Singulatiry server and all seems to be ok. 
Unfortunately none of payloads work :( 
I am running them on my Laptop on MacOS and I have tried also on WIndows VM.
From the Singularity server I am receiving these logs when using "Simple Fetch Get" payload and "First and second" strategy.
<img width="1079" alt="screen with error" src="https://user-images.githubusercontent.com/37508395/81511604-d9c1a200-931a-11ea-8997-eb79f31f771e.png">

It should work, but it does't. Where might be a problem?
Thank you for any help

**Comment by gdncc** [comment]
Can you please provide the output of command `curl --header "Host: attacker.com" http://192.168.1.48:80/` and of `curl http://192.168.1.48:80/`.

**Comment by grenej** [comment]
Hi,

Service is vulnerable. I thing this is not an error of the service accessibility, but something else.
<img width="938" alt="screen1" src="https://user-images.githubusercontent.com/37508395/81512179-e9db8080-931e-11ea-8c73-1848dcf3b062.png">
<img width="920" alt="screen2" src="https://user-images.githubusercontent.com/37508395/81512180-eb0cad80-931e-11ea-94f3-2afab44365e2.png">

**Comment by gdncc** [comment]
Did you test your setup as described in https://github.com/nccgroup/singularity/wiki/Setup-and-Installation#testing-the-setup?

**Comment by grenej** [comment]
yes. the same results when deploying test service locally

**Comment by gdncc** [comment]
Can you show the output of your browser console when testing the local service.

**Comment by gdncc** [comment]
What you highlighted in red is not an error message by the way. I've updated the code to make the log message less confusing.

**Comment by grenej** [comment]
Hi,

I setup local http server (based on python) according to your advices on wiki. This time on Windows 10 machine. The same results.
Here are results from Chrome console when connecting to 127.0.0.1 service.
<img width="1432" alt="console screen" src="https://user-images.githubusercontent.com/37508395/81559874-8a1dbd80-9390-11ea-8a39-6db6558e14a9.png">
Log from the server:
<img width="1177" alt="server screen" src="https://user-images.githubusercontent.com/37508395/81559875-8be78100-9390-11ea-8ec3-76400d711106.png">

**Comment by gdncc** [comment]
It looks like the browser never received the first DNS response.

* Can you test that the simple fetch payload using the First then Second strategy against the local python service works on http://rebind.it/ . Use defaults for now: 20 second interval (not 1 second) and no cache flooding. This is mostly to rule out configuration issues with your setup.
* If it does not work, can you try changing your system DNS to point to 8.8.8.8 instead of your ISP's DNS servers and test again. This is to rule out issues with your ISP DNS configuration.

**Comment by grenej** [comment]
Thank you for answer.

According to your scenarios:

1. Doesn't work. The same errors that I have. It look like browser never received the first DNS response.

2.When I changed DNS on my Windows VM to 8.8.8.8 it works with rebind.it. But with my config still problems. I will put results when I restart the server.  What might be wrong with my ISP DNS? These are 2 IP's wich were assigned by DHPC from the router.

**Comment by grenej** [comment]
Ok. My server also work when I changed on the victim machine DNS to 8.8.8.8. So here is the problem. Does it mean that ISP  has a solution to protect by this attack?

**Comment by gdncc** [comment]
I am leaning towards the possibility that the ISP DNS servers or other devices (IDS) cause out of order or spurious DNS requests and responses.

One way to potentially determine this is to make a few (3-5) DNS lookups e.g. using `nslookup` on Windows to "s-13.x.x.x-127.0.0.1-1-fs-e.dynamic.attacker.com" then observe the order of responses (it should be 13.x.x.x and then 127.0.0.1). Repeat the test by bumping the session ID e.g. "s-13.x.x.x-127.0.0.1-2-fs-e.dynamic.attacker.com" and so on. Finally, try to confirm the hypothesis based on the observed results.

If confirmed, one way to attack in this scenario is to use the random DNS rebinding strategy. It may take several minutes or less if you are lucky - try to wait 10 min. You will see errors in the framed window but you can ignore that. One could possibly run several attacks in one page to increase the attack speed but you would have to write your own "autoattack.html" to do this.

Finally, it would be interesting to test the multiple answers DNS rebinding strategy. This won't work for your printer but it would work for a localhost service if not disturbed by your ISP setup. For this attack on Windows,  you should set the target to "127.0.0.1", the interval to 1 second and disable DNS cache flooding.

**Comment by grenej** [comment]
thanks for comment.
