### ISSUE TITLE
[wiki] Add -r to copy payloads directory

### ISSUE THREAD

**Issue by nikitastupin** [nccgroup/singularity#32]
Hi,

Thanks for the framework! I've just followed an [installation instructions](https://github.com/nccgroup/singularity/wiki/Setup-and-Installation#deploy) and noticed that `$ cp ~/go/src/github.com/nccgroup/singularity/html/* ~/singularity/html/` produces and error `cp: -r not specified; omitting directory ...`.

Please consider adding `-r` option to this command on [wiki page](https://github.com/nccgroup/singularity/wiki/Setup-and-Installation#deploy) :)

**Comment by gdncc** [comment]
Hi, thank you! This is now fixed.
