### ISSUE TITLE
Initial "Go Get" command does not create ~/go/src/github.com/nccgroup/singularity/cmd/singularity-server

### ISSUE THREAD

**Issue by mikedesu** [nccgroup/singularity#37]
Hello.

A student contacted me requesting help setting up a singularity server. I span up a debian 10 vm to try this out before we meet tonight. 

After installing go and after installing the specified packages, there is no folder to cd into as suggested by the setup instructions.

```
   go get -v github.com/nccgroup/singularity
   go get -v github.com/gorilla/mux
   go get -v github.com/gorilla/websocket
   go get -v github.com/gorilla/securecookie
   cd ~/go/src/github.com/nccgroup/singularity/cmd/singularity-server
   -bash: cd: /root/go/src/github.com/nccgroup/singularity/cmd/singularity-server: No such file or directory
```

This tool seems interesting, but I am unable to proceed with the installation past this point and won't be able to assist my student further as a result. I've informed them to inform their professor that the instructions might be out-of-date (as it appears). 

Were someone to want to proceed forward on a new box, how might we go about doing this?

**Comment by sanktjodel** [comment]
- Which go version do you have?
- How did you install go (apt or manual installation)?
- Did you try running the installation under a regular user?

**Comment by mikedesu** [comment]
- 1.16.3
- From the official go website, as per the instructions (download and untar)
- I did not, will give a try again as a regular user

**Comment by sanktjodel** [comment]
For golang version 1.16.x, please use the following workaround:
```
$ git clone https://github.com/nccgroup/singularity
$ cd singularity/cmd/singularity-server/
$ go build
```
After compilation, don't forget to update your local file system paths to wherever you cloned the repository to instead of ~/go/src/github.com/nccgroup/singularity for the next installation steps.

We will be updating the installation instructions.

**Comment by sanktjodel** [comment]
Thank you for letting us know. We have updated the installation instructions at https://github.com/nccgroup/singularity/wiki/Setup-and-Installation to cater for changes in Go module system. Closing this issue.
