### ISSUE TITLE
Singularity won't compile even with latest go version

### ISSUE THREAD

**Issue by rew1nter** [nccgroup/singularity#40]
When I try to build the main.go file it shows up with code error and fails to compile. Tried it on two windows machines with different go versions.
![Screenshot_719-1](https://user-images.githubusercontent.com/64508791/120904552-aa40ae80-c66e-11eb-81a9-a18a1f3932bf.png)
Both failed

**Comment by gdncc** [comment]
Singularity of Origin runs only on Linux (but  can be [cross-compiled](https://github.com/nccgroup/singularity/wiki/Useful-Notes-and-Other-Loose-Ends)). Specifically, it requires `iptables` to dynamically manage firewall rules for the "Multiple answers" rebinding technique,  and Linux IP [transparent proxy](https://www.kernel.org/doc/html/latest/networking/tproxy.html) to redirect many ports to one port (the latter is admittedly a convenience feature).

**Comment by rew1nter** [comment]
You mentioned the browser based control in docs.
Is it possible to run Singularity of origin in Ubuntu server with no GUI?

**Comment by rew1nter** [comment]
You documented browser based control.
Is it possible to use Singularity of origin without GUI access on Linux server?
