### ISSUE TITLE
DNS rebinding failed on Ubuntu 20.04.1 LTS

### ISSUE THREAD

**Issue by ttttmr** [nccgroup/singularity#45]
![image](https://user-images.githubusercontent.com/32825326/147641616-2638a8b2-4a65-4194-8b57-8e968983fca3.png)

OS: Ubuntu 20.04.1 LTS

I used the default version (79.0) of Firefox at first, and then I tried to upgrade Firefox to the latest version (95.0.1), but it failed.

It seems that the local service is directly accessed, and it is a 404 directly.

I tried 127.0.0.1 again and it failed

**Comment by ttttmr** [comment]
This is the dns query result

![image](https://user-images.githubusercontent.com/32825326/147646525-801596fe-b1bb-405e-ad7e-c90481f2e254.png)
![image](https://user-images.githubusercontent.com/32825326/147646654-381fd46f-bc6f-4696-9da1-ce7e9ab0be4c.png)

I tried a lot of this without rebinding successfully

**Comment by sanktjodel** [comment]
Hi

I just successfully tried the "First then second" and "Multiple answers" rebinding strategies on Ubuntu 21.10 with Firefox 95.0.2. 

Did you verify that the target service is vulnerable to DNS rebinding (https://github.com/nccgroup/singularity/wiki/Testing-for-Vulnerable-Services)?

I suggest to try the default "First then second" rebinding strategy first as it's the most reliable. 

Did it work with Firefox 79.0?

If you still have issues, please provide some more information about the target service such as the output of `curl -v --header "Host: attacker.com" http://127.0.0.1:8000/` and of `curl -v http://127.0.0.1:8000/`

**Comment by ttttmr** [comment]
Sorry, I found the reason, it's my network problem
