### ISSUE TITLE
Origin check fails when using port 80

### ISSUE THREAD

**Issue by lean0x2F** [nccgroup/singularity#9]
There is a bug on the origin definition on `FrameManager` on manager.js.

```javascript
    const origin = (url) => {
        //Does not work in IE11. 
        //const u = new URL(url); 
        // Workaround:
        let u = document.createElement('a');
        let id = Math.random().toString();
        u.setAttribute('href', url);
        u.setAttribute('id', id);
        const o = `${u.protocol}//${u.hostname}:${u.port}`; // <---- HERE
        u.remove();
        return o;
    };
```

`u.port` would be empty if the port is 80 (because browsers remove it from a url when using 80). That would cause the origin to be "example.com:" instead of "example.com"

Change that line for:

```javascript
const o = u.port ? `${u.protocol}//${u.hostname}:${u.port}`: `${u.protocol}//${u.hostname}`;
```
 
By the way, great tool, thank you!

**Comment by gdncc** [comment]
Fixed in commit https://github.com/nccgroup/singularity/commit/7431301bae628a8838f015ae61ed60954a4a7779. Thank you!
